[package]
name = "cookie"
authors = ["Alex Crichton <alex@alexcrichton.com>", "Sergio Benitez <sb@sergio.bz>"]
version = "0.13.3"
license = "MIT/Apache-2.0"
repository = "https://github.com/SergioBenitez/cookie-rs"
documentation = "https://docs.rs/cookie"
description = """
Crate for parsing HTTP cookie headers and managing a cookie jar. Supports signed
and private (encrypted + signed) jars.
"""

[features]
secure = ["ring", "base64"]
percent-encode = ["percent-encoding"]

[dependencies]
time = { version = "0.2.6", default-features = false, features = ["std"] }
percent-encoding = { version = "2.1.0", optional = true }
ring = { version = "0.16.11", optional = true }
base64 = { version = "0.11.0", optional = true }

[package.metadata.docs.rs]
all-features = true
